name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Make Gradle wrapper executable (Linux/macOS only)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts (only on Linux + Java 21)
        if: runner.os == 'Linux' && matrix.java == 21
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
